language: scala
sudo: required
scala:
   - 2.12.1

jdk:
  - oraclejdk8 

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt clean
  - sbt ++$TRAVIS_SCALA_VERSION test
